// This file was generated by Prisma
import { loadEnvFile } from 'node:process';
import { defineConfig } from 'prisma/config';

loadEnvFile(`.env.${process.env.NODE_ENV ?? 'development'}`);

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
