@userId = {{ '7c78714d-d603-4a57-bdfa-8fd4946a0408' }}

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### List users
GET http://localhost:3000/users

### Get user by id
GET http://localhost:3000/users/{{userId}}

### Update user
PATCH http://localhost:3000/users/{{userId}}
Content-Type: application/json

{
  "email": "updated@example.com"
}

### Delete user
DELETE http://localhost:3000/users/{{userId}}
