### Get current user
GET {{host}}/app/users/me
Authorization: Bearer {{token}}

### Update current user's email
PATCH {{host}}/app/users/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "updated@example.com"
}

### Update current user's password
PATCH {{host}}/app/users/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "new-password123"
}

### Delete current user
# Allowed only when the user has no cart or orders.
DELETE {{host}}/app/users/me
Authorization: Bearer {{token}}
