@orderItemId = {{ '' }}
@orderId = {{ '' }}
@productId = {{ '' }}

### Create order item
POST http://localhost:3000/order-items
Content-Type: application/json

{
  "orderId": "{{orderId}}",
  "productId": "{{productId}}",
  "quantity": 1,
  "unitPrice": 9.99
}

### List order items
GET http://localhost:3000/order-items

### Get order item by id
GET http://localhost:3000/order-items/{{orderItemId}}

### Update order item
PATCH http://localhost:3000/order-items/{{orderItemId}}
Content-Type: application/json

{
  "quantity": 2
}

### Delete order item
DELETE http://localhost:3000/order-items/{{orderItemId}}
