@categoryId = 5f7638bc-2199-4d71-85ca-a14aecb54983

### Create category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Category 1",
  "description": "Description 1"
}

### List categories
GET http://localhost:3000/categories

### Get category by id
GET http://localhost:3000/categories/{{categoryId}}

### Update category
PATCH http://localhost:3000/categories/{{categoryId}}
Content-Type: application/json

{
  "name": "Category 3"
}

### Delete category
DELETE http://localhost:3000/categories/{{categoryId}}
