@categoryId = 5f7638bc-2199-4d71-85ca-a14aecb54983

### Create category
POST {{host}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Category 1",
  "description": "Description 1"
}

### List categories
GET {{host}}/categories
Authorization: Bearer {{token}}

### Get category by id
GET {{host}}/categories/{{categoryId}}
Authorization: Bearer {{token}}

### Update category
PATCH {{host}}/categories/{{categoryId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Category 3"
}

### Delete category
DELETE {{host}}/categories/{{categoryId}}
Authorization: Bearer {{token}}
