@categoryId = 5f7638bc-2199-4d71-85ca-a14aecb54983

### App: list categories
GET {{host}}/app/categories
Authorization: Bearer {{token}}

### App: get category by id
GET {{host}}/app/categories/{{categoryId}}
Authorization: Bearer {{token}}

### Dashboard: create category
POST {{host}}/dashboard/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Category 1",
  "description": "Description 1"
}

### Dashboard: list categories
GET {{host}}/dashboard/categories
Authorization: Bearer {{token}}

### Dashboard: get category by id
GET {{host}}/dashboard/categories/{{categoryId}}
Authorization: Bearer {{token}}

### Dashboard: update category
PATCH {{host}}/dashboard/categories/{{categoryId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Category 3"
}

### Dashboard: delete category
DELETE {{host}}/dashboard/categories/{{categoryId}}
Authorization: Bearer {{token}}
