@cartItemId = {{ '' }}
@cartId = {{ '' }}
@productId = {{ '' }}

### Create cart item
POST http://localhost:3000/cart-items
Content-Type: application/json

{
  "cartId": "{{cartId}}",
  "productId": "{{productId}}",
  "quantity": 1
}

### List cart items
GET http://localhost:3000/cart-items

### Get cart item by id
GET http://localhost:3000/cart-items/{{cartItemId}}

### Update cart item
PATCH http://localhost:3000/cart-items/{{cartItemId}}
Content-Type: application/json

{
  "quantity": 2
}

### Delete cart item
DELETE http://localhost:3000/cart-items/{{cartItemId}}
